variables:
  vmImage: RipplesSelfHostedPool

trigger:
  - main

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        displayName: "Build"
        pool: $(vmImage)
        steps:
          - checkout: self
          - task: Maven@3
            inputs:
              mavenPomFile: "pom.xml"
              goals: "clean package"

          - task: Docker@2
            inputs:
              containerRegistry: "Shanmu Docker Hub" # Modify this with your Docker registry connection
              repository: "shanmutp/spring_image_azure" # Modify this with your Docker image repository name
              command: "build"
              Dockerfile: "**/DockerFile"
              tags: "latest"
              buildContext: "$(Build.SourcesDirectory)/target"

          - task: Docker@2
            inputs:
              containerRegistry: "Shanmu Docker Hub" # Modify this with your Docker registry connection
              repository: "shanmutp/spring_image_azure" # Modify this with your Docker image repository name
              command: "push"
              tags: "latest"

  #- stage: Test
  #  jobs:
  # - job: TestJob
  #    displayName: 'Test'
  #   dependsON: Build
  #  condition: succeeded()
  # pool:
  #  vmImage: 'ubuntu-latest'
  #steps:
  #- checkout: self
  #- script: echo Running tests...

  - stage: Deploy
    jobs:
      - job: DeployJob
        displayName: "Deploy"
        pool: $(vmImage)
        steps:
          - checkout: self
          - task: AzureRmWebAppDeployment@4
            inputs:
              azureSubscription: "AzureSpringBootWebServer"
              appType: "webApp"
              appName: "RipplesSpringBootWebApp"
              containers: "shanmutp/spring_image_azure"
